# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              ML Cookbook
description:        ML Cookbook
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://ml-book.com"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:           Andrew Wolf
    title:          Founder
    avatar:         andrew.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    victor:
      name:         Victor Popov
      title:        Applied ML Lead
      avatar:       victor.jpeg
    gwena:
      name:         Gwena Cunha
      title:        NLP Lead
      avatar:       gwena.jpg
    rex:
      name:         Rex Cheung
      title:        Statistics Lead
      avatar:       rex.png
    kirill:
      name:         Kirill Zaznobin
      title:        Development Lead
      avatar:       kirill.jpeg
    andrew:
      name:         Andrew Wolf
      title:        Founder
      avatar:       andrew.jpeg

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/thelearningm
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/thelearningm
    linkedin:
    pinterest:
    twitter:
    vimeo:
    youtube:

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      Made by a <a href="https://5x12.github.io/">human</a> somewhere on the planet earth.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc

